import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <header className="navbar">
          <Navbar />
        </header>
        <main>
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
        </main>
        <footer className="footer">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
